### ISSUE TITLE
[6.0] Avatar not saved on database

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#6695]
**Describe the bug**

**To Reproduce**
1. upload avatar
2. Check if image is on database

**Expected behavior**
saved

**Actual result**
not saved

**Comment by 810** [comment]
ok looks like the new created user by backend is missing as kunena user.

**Comment by rich20** [comment]
The avatar is saved in the database. If you switch the Avatar type from Icontype to Image you see the Avatar correct.
There is a wrong path when set is Icontype
/media/kunena/" core="" svg="" person.svg"="" width="32" height="32">

**Comment by 810** [comment]
should be fixed, try again

**Comment by rich20** [comment]
There are more mistake.
**Default configuration setting:** 
Avatar type = Icontype
**Default template setting:**
Icon type = bootstrap 4
- [x] The uploaded avatar will be displayed
- [x] It's not possible to change the view to Circle, Rounded or Thumbnail
- [x] If you don't upload an avatar, it shows a svg with wrong size (see image)

![Bildschirmfoto von 2020-01-02 14-54-40](https://user-images.githubusercontent.com/888847/71670935-d79a7600-2d71-11ea-928d-2ebd43187f3a.png)  

**Default configuration setting:** 
Avatar type = Icontype
**Template setting:**
Icon type = Fontawesome
- [ ] Instead of the uploaded Avatar it shows fas fa-user
- [x] If you don't upload an avatar, it shows the person.svg

**Comment by 810** [comment]
can you recheck everything?

**Comment by rich20** [comment]
This error still exist.
**Default configuration setting:** 
Avatar type = Icontype
**Template setting:**
Icon type = Fontawesome
- [ ] Instead of the uploaded Avatar it shows fas fa-user
